swagger: '2.0'
info:
  version: 1.0.0
  title: Pet Store API
  description: An API for managing pets in a store
  termsOfService: http://example.com/terms-of-service
  contact:
    name: Pet Store Support
    email: support@example.com
  license:
    name: MIT
    url: http://opensource.org/licenses/MIT
host: petstore.example.com
basePath: /v1
schemes:
  - http
  - https
consumes:
  - application/json
produces:
  - application/json
paths:
  /pets:
    get:
      summary: List all pets
      operationId: listPets
      responses:
        200:
          description: Successful operation
          schema:
            type: array
            items:
              $ref: '#/definitions/Pet'
    post:
      summary: Create a new pet
      operationId: createPet
      parameters:
        - name: pet
          in: body
          description: Pet object to be added to the store
          required: true
          schema:
            $ref: '#/definitions/Pet'
      responses:
        200:
          description: Successful operation
  /pets/{petId}:
    get:
      summary: Find pet by ID
      operationId: getPetById
      parameters:
        - name: petId
          in: path
          description: ID of pet to return
          required: true
          type: integer
          format: int64
      responses:
        200:
          description: Successful operation
          schema:
            $ref: '#/definitions/Pet'
        404:
          description: Pet not found
    delete:
      summary: Delete pet by ID
      operationId: deletePet
      parameters:
        - name: petId
          in: path
          description: ID of pet to delete
          required: true
          type: integer
          format: int64
      responses:
        204:
          description: Pet deleted
  /pets/{petId}/uploadImage:
    post:
      summary: Upload an image for a pet
      operationId: uploadPetImage
      parameters:
        - name: petId
          in: path
          description: ID of pet to upload an image for
          required: true
          type: integer
          format: int64
        - name: additionalMetadata
          in: formData
          description: Additional data to pass
          required: false
          type: string
        - name: file
          in: formData
          description: File to upload
          required: false
          type: file
      responses:
        200:
          description: Successful operation

definitions:
  Pet:
    type: object
    properties:
      id:
        type: integer
        format: int64
      name:
        type: string
      photoUrls:
        type: array
        items:
          type: string
      status:
        type: string
      tags:
        type: array
        items:
          type: string
